site_name: Sinlib Documentation
site_description: Documentation for Sinlib
site_author: Ransaka Ravihara

repo_url: https://github.com/Ransaka/sinlib
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/custom_theme
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - mkdocs-jupyter:
      include_source: true
      execute: false
      ignore_h1_titles: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - css/custom.css
  - css/extra.css

nav:
  - Home: index.md
  - Examples:
    - Tokenization Example: examples/Tokenization Example.md
    - Typo Correction: examples/Typo Correction.md